## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: SmartHotel_RegistrationApplication
  properties:
    services:
      - name: SmartHotel_Registration_Wcf
        properties:
          description: SmartHotel_Registration_Wcf description.
          osType: Windows
          codePackages:
            - name: SmartHotel_Registration_Wcf
              image: smarthotelregistrationwcf:dev
              endpoints:
                - name: SmartHotel_Registration_WcfListener
                  port: 88
              environmentVariables:
                - name: AppInsightsKey
                  value: "<Place AppInsights key here, or reference it via a secret>"
                - name: DefaultConnection
                  value: "Data Source=tcp:', reference(concat('Microsoft.Sql/servers/', variables('sqlserverName'))).fullyQualifiedDomainName, ',1433;Initial Catalog=', variables('databaseName'), ';Persist Security Info=False;User Id=', parameters('sqlAdministratorLogin'), '@', reference(concat('Microsoft.Sql/servers/', variables('sqlserverName'))).fullyQualifiedDomainName, ';Password=', parameters('sqlAdministratorLoginPassword'), ';MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: SmartHotel_RegistrationApplicationNetwork