## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: SmartHotel_RegistrationApplication
  properties:
    services:
      - name: SmartHotel_Registration_KPI
        properties:
          description: SmartHotel_Registration_KPI description.
          osType: Windows
          codePackages:
            - name: SmartHotel_Registration_KPI
              image: smarthotelregistrationkpi:dev
              endpoints:
                - name: SmartHotel_Registration_KPIListener
                  port: 20009
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20009
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
              reliableCollectionsRefs:
                - name: SmartHotel_Registration_KPICollections
          replicaCount: 1
          networkRefs:
            - name: SmartHotel_RegistrationApplicationNetwork